### ISSUE TITLE
force closes

### ISSUE THREAD

**Issue by unknownLincoln** [Faguss/odol2mlod#1]
when i open it, it closes right away, how do i use it?

**Comment by Faguss** [comment]
From the command line. Or drag & drop p3d file over it.

**Comment by unknownLincoln** [comment]
![image](https://github.com/Faguss/odol2mlod/assets/81295931/657acf98-524d-4a74-a294-e3c50a340ce5)
I get this error when importing it to blender using Arma toolbox, do you know why?

**Comment by Faguss** [comment]
Arma toolbox is for Arma3 models. odol2mlod is for OFP models. Here's a converter for Arma3 models: https://github.com/Crip12/P3D-Debinarizer-Arma-3

For opening OFP models in Blender there's this plugin: http://ofpr.info.paradoxstudio.uk/309-blender-2-49-plugin-tutorials.html
