### ISSUE TITLE
it says "I/O error: unpack requires a buffer of 4 bytes" and "I/O error: Exception while reading when i try to import mdol p3d file into blender.

### ISSUE THREAD

**Issue by Fisheks** [Faguss/odol2mlod#2]

**Comment by Faguss** [comment]
[Armatoolbox](https://github.com/AlwarrenSidh/ArmAToolbox) does not support MLOD SP3X (old format). You have to convert it first to the MLOD P3DM (newer format) using O2pe or Object Builder and only then import it in Blender.

**Comment by Fisheks** [comment]
> [Armatoolbox](https://github.com/AlwarrenSidh/ArmAToolbox) does not support MLOD SP3X (old format). You have to convert it first to the MLOD P3DM (newer format) using O2pe or Object Builder and only then import it in Blender.

https://github.com/Crip12/P3D-Debinarizer-Arma-3
I found that Crip12's P3D Debinarizer its working well for Armatoolbox. You can put it in description for people who wanna import arma 3 models into blender.

**Comment by Faguss** [comment]
I'll do that. Thanks.
