### ISSUE TITLE
empty mlod 

### ISSUE THREAD

**Issue by HenriqueFerreira7** [Faguss/odol2mlod#3]
when I try to unbinarize odol model, it gives me an empty mlod model

terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append

**Comment by Faguss** [comment]
Send me the file and I'll take a look

**Comment by HenriqueFerreira7** [comment]
the empty mlod p3d?

**Comment by Faguss** [comment]
The source file so that I can repeat the error myself.

**Comment by HenriqueFerreira7** [comment]
[C50.zip](https://github.com/user-attachments/files/15827226/C50.zip)
here

**Comment by Faguss** [comment]
That's ARMA 2/3 model. Use [this program](https://github.com/Crip12/P3D-Debinarizer-Arma-3) instead.
